// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _RcppSqEM_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// squarem1_cpp
Rcpp::List squarem1_cpp(Rcpp::NumericVector par, SEXP fixptfn, SEXP objfn, const Rcpp::List& ctrl, SEXP env);
RcppExport SEXP _RcppSqEM_squarem1_cpp(SEXP parSEXP, SEXP fixptfnSEXP, SEXP objfnSEXP, SEXP ctrlSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixptfn(fixptfnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type objfn(objfnSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ctrl(ctrlSEXP);
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    rcpp_result_gen = Rcpp::wrap(squarem1_cpp(par, fixptfn, objfn, ctrl, env));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSqEM_rcpp_hello", (DL_FUNC) &_RcppSqEM_rcpp_hello, 0},
    {"_RcppSqEM_squarem1_cpp", (DL_FUNC) &_RcppSqEM_squarem1_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSqEM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
