# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

squarem1_cpp <- function(par, fixptfn, objfn, ctrl, env) {
    .Call(`_RcppSqEM_squarem1_cpp`, par, fixptfn, objfn, ctrl, env)
}

squarem2_cpp <- function(par, fixptfn, ctrl, env) {
    .Call(`_RcppSqEM_squarem2_cpp`, par, fixptfn, ctrl, env)
}

